modLoader = "javafml"
loaderVersion = "[43,)"
license = "MIT"
[[mods]]
    modId = "arcanism"
    version = "${file.jarVersion}"
    displayName = "Arcanism"
    description = '''

    '''

[[dependencies.arcanism]]
    modId = "forge"
    mandatory = true
    versionRange = "[43,)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.arcanism]]
    modId = "minecraft"
    mandatory = true
    versionRange = "[1.19,1.19.2)"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.arcanism]]
    modId = "patchouli"
    mandatory = true
    versionRange = "[1.19.2-77,)"
    ordering = "AFTER"
    side = "BOTH"

[[dependencies.arcanism]]
    modId="curios"
    mandatory=true
    versionRange="[1.19.2-5.1.1.0,)"
    ordering = "AFTER"
    side = "BOTH"